
###
POST http://localhost:5000/api/translate HTTP/1.1
content-type: application/json

{
    "srcLanguage": "eng",
    "targetLanguage": "med",
    "text": "Yes"
}

###
POST http://localhost:5000/api/translate HTTP/1.1
content-type: application/json

{
    "srcLanguage": "eng",
    "targetLanguage": "med",
    "text": "Yes"
}


###
POST https://sleepy-depths-05281.herokuapp.com/api/translate HTTP/1.1
content-type: application/json

{
    "srcLanguage": "eng",
    "targetLanguage": "med",
    "text": "Yes"
}